version: "3.4"
services:
  web:
    container_name: react_app
    build: .
    ports:
    - "3000:3000"
    - "4000:4000"
    volumes:
    - '.:/app'
    - '/app/node_modules'
    - '/app/backend/node_modules'
    environment:
    - CHOKIDAR_USEPOLLING=true
    - REACT_APP_MONGO_URL=mongodb://mongo:27017
    - REACT_APP_HOSTNAME=http://localhost:4000
    stdin_open: true
    tty: true
  mongo:
    container_name: mongo
    image: mongo:4.4.1
    ports:
    - "27017:27017"
