apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: brian-mernstack-build
  name: brian-mernstack-build-config
spec:
  failedBuildsHistoryLimit: 2
  source:
    type: Git
    git:
      uri: https://github.com/melosaiyan/react_mernstack_local.git
      ref: openshift
    contextDir: app
  output:
    to:
      kind: DockerImage
      name: mernstack:latest
  runPolicy: Serial
  strategy:
    type: Docker
  successfulBuildsHistoryLimit: 2